spring:
  application:
    name: lifelink
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/lifelink
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show_sql: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

debug: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.web: DEBUG

AI_SERVICE_URL: ${AI_SERVICE_URL:http://localhost:8000}

INTERSWITCH:
  PAYMENT_CLIENT_ID: ${INTERSWITCH_PAYMENT_CLIENT_ID}
  PAYMENT_CLIENT_SECRET: ${INTERSWITCH_PAYMENT_CLIENT_SECRET}
  PAYMENT_MERCHANT_CODE: ${INTERSWITCH_PAYMENT_MERCHANT_CODE}
  PAYMENT_PAYID: ${INTERSWITCH_PAYMENT_PAYID}
  VERIFICATION_CLIENT_ID: ${INTERSWITCH_VERIFICATION_ID}
  VERIFICATION_CLIENT_SECRET: ${INTERSWITCH_VERIFICATION_SECRET}